packages:
  - notion-zodify
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@notionhq/client': ^2.3.0
  astro: ^5.7.10
  eslint: ^9.24.0
  eslint-plugin-format: ^1.0.1
  typescript: 5.8.3
  vitest: ^3.1.2
